#!/usr/bin/env python3
"""Regenerate SOURCES.md from data/config.json.

The committed config.json is the source of truth for what we subscribe to.
SOURCES.md is a human-friendly view of the same data, regenerated by CI on
every push that touches config.json so the two never drift.

Do not edit SOURCES.md by hand — your changes will be overwritten.
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONFIG_PATH = ROOT / "data" / "config.json"
OUT_PATH = ROOT / "SOURCES.md"


def _is_on(node: dict) -> bool:
    """Treat missing `enabled` as enabled (matches Horizon's runtime behavior)."""
    return node.get("enabled", True)


def render() -> str:
    cfg = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
    ai = cfg.get("ai", {})
    sources = cfg.get("sources", {})
    filtering = cfg.get("filtering", {})

    out: list[str] = [
        "# Subscribed Sources",
        "",
        "_Auto-generated from `data/config.json` by `.github/workflows/sources-md.yml`._",
        "_Do not edit by hand — edit `data/config.json` instead._",
        "",
        f"Last regenerated: `{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}`",
        "",
        "## AI",
        "",
        f"- Provider: `{ai.get('provider', '?')}`  ·  Model: `{ai.get('model', '?')}`",
        f"- Output languages: {', '.join(f'`{lng}`' for lng in ai.get('languages', []))}",
        "",
        "## Filtering",
        "",
        f"- `ai_score_threshold`: **{filtering.get('ai_score_threshold')}**",
        f"- `time_window_hours`: {filtering.get('time_window_hours')}",
        "",
    ]

    # RSS — grouped by category for readability
    rss = [r for r in sources.get("rss", []) if _is_on(r)]
    if rss:
        out += ["## RSS", ""]
        by_cat: dict[str, list[dict]] = {}
        for r in rss:
            by_cat.setdefault(r.get("category", "uncategorized"), []).append(r)
        for cat in sorted(by_cat):
            out += [f"### {cat}", ""]
            for r in by_cat[cat]:
                out.append(f"- [{r['name']}]({r['url']})")
            out.append("")

    # Hacker News
    hn = sources.get("hackernews", {})
    if _is_on(hn):
        out += [
            "## Hacker News",
            "",
            f"- Top {hn.get('fetch_top_stories', '?')} stories, "
            f"min HN score {hn.get('min_score', '?')}",
            "",
        ]

    # Reddit
    red = sources.get("reddit", {})
    if _is_on(red):
        subs = [s for s in red.get("subreddits", []) if _is_on(s)]
        if subs:
            out += ["## Reddit", ""]
            for s in subs:
                out.append(
                    f"- r/{s['subreddit']} "
                    f"({s.get('sort', 'hot')}/{s.get('time_filter', '-')}, "
                    f"min score {s.get('min_score', '?')}, "
                    f"limit {s.get('fetch_limit', '?')})"
                )
            users = [u for u in red.get("users", []) if _is_on(u)]
            if users:
                out.append("")
                for u in users:
                    out.append(f"- u/{u['username']} ({u.get('sort', 'new')})")
            out.append("")

    # GitHub
    gh = [g for g in sources.get("github", []) if _is_on(g)]
    if gh:
        out += ["## GitHub", ""]
        for g in gh:
            kind = g.get("type", "?")
            if kind == "repo_releases":
                out.append(f"- releases: `{g.get('owner')}/{g.get('repo')}`")
            elif kind == "user_events":
                out.append(f"- user activity: `{g.get('username')}`")
            else:
                out.append(f"- {kind}: `{g.get('owner', g.get('username', '?'))}`")
        out.append("")

    # Telegram (channels scraped as a source — Phase 2/Phase 4.5 will add some)
    tg = sources.get("telegram", {})
    if _is_on(tg) and tg.get("channels"):
        chans = [c for c in tg["channels"] if _is_on(c)]
        if chans:
            out += ["## Telegram channels (scraped)", ""]
            for c in chans:
                out.append(f"- @{c['channel']} (last {c.get('fetch_limit', '?')} messages)")
            out.append("")

    return "\n".join(out).rstrip() + "\n"


def main() -> None:
    OUT_PATH.write_text(render(), encoding="utf-8")
    print(f"wrote {OUT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
